/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bell_abdi;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javazoom.jl.player.Player;;;

import sun.audio.*;
import javax.swing.*; 
import java.io.*;
import java.net.URL;

/**
 *
 * @author Windows Pro
 */
public class Bell_form extends javax.swing.JDialog {
String termin_jv;
private static String filename;
private static Player player;

    /**
     * Creates new form Bell_form
     */
    public Bell_form(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        run();
        //suara();
    }
    
    public void run() {  
    new Thread() {  
        public void run() {  
            int waktu = 0;  
            while (waktu == 0) {  
                Calendar kalender = new GregorianCalendar();  
                  
                //set variabel  
                int jam = kalender.get(Calendar.HOUR);  
                int menit = kalender.get(Calendar.MINUTE);  
                int detik = kalender.get(Calendar.SECOND);  
                int am_pm = kalender.get(Calendar.AM_PM);  
                  
                //mengatur menggunakan AM atau PM  
                String siang_malam = "";  
                if (am_pm == 1) {  
                    siang_malam = "PM";  
                } else {  
                    siang_malam = "AM";  
                }  
                  
                //mengatur format penulisan waktu  
                String format_waktu = jam + ":" + menit + ":" + detik + " " + siang_malam;  
  
                //menampilkan pada label yang digunakan sebagai penunjuk waktu  
                txtJam.setText(format_waktu);  
            }  
        }  
    }.start();
    }
    
    void control_jam(){
        Calendar c = Calendar.getInstance();
        int timeOfDay = c.get(Calendar.HOUR_OF_DAY);

        if (timeOfDay >= 0 && timeOfDay < 12) {
            termin_jv = "Pagi";
        } else if (timeOfDay >= 12 && timeOfDay < 16) {
            termin_jv = "Siang";
        } else if (timeOfDay >= 16 && timeOfDay < 21) {
            termin_jv = "Sore";
        } else if (timeOfDay >= 21 && timeOfDay < 24) {
            termin_jv = "Malam";
        }
    }
    
    
    public static void play_sound(String control) {
        InputStream music;
        try{
          music=new FileInputStream(new File("src\\bell_abdi.wav"));
          AudioStream audios=new AudioStream(music);
          if(control.equals("On")){
              AudioPlayer.player.start(audios);
          }else if(control.equals("Off")){
              AudioPlayer.player.stop(audios);
          }
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
        }                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        txtJam = new javax.swing.JLabel();
        btnSuara = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtJam.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        txtJam.setForeground(new java.awt.Color(255, 0, 0));
        txtJam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJam.setText("jLabel1");

        btnSuara.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSuara.setText("Start");
        btnSuara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaraActionPerformed(evt);
            }
        });

        jLabel1.setText("Programmed By : Ari - Alaram Abdi Apps");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtJam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSuara, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(txtJam)
                .addGap(13, 13, 13)
                .addComponent(btnSuara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaraActionPerformed
        // TODO add your handling code here:
        if(btnSuara.getText().equals("Start")){
            btnSuara.setText("On");
        }else if(btnSuara.getText().equals("On")){
            btnSuara.setText("Off");
            play_sound("On");
        }else if(btnSuara.getText().equals("Off")){
            btnSuara.setText("Start");
            play_sound("Off");
        }
    }//GEN-LAST:event_btnSuaraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bell_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bell_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bell_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bell_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Bell_form dialog = new Bell_form(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuara;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel txtJam;
    // End of variables declaration//GEN-END:variables
}
